### ISSUE TITLE
Issues with the simulation code in MATLAB R2017b due to wavread/wavwrite

### ISSUE THREAD

**Issue by ericye16** [fgnt/nn-gev#4]
I was having issues running the simulate data code in R2017b since wavread and wavwrite have been removed. I submitted a pull request to address this: #3 if you are interested in using this code with modern MATLAB in the future.

**Comment by jheymann85** [comment]
Merged PR. Guess newer versions of Matlab with `audioread` instead of `wavread` are more commonly used.
