### ISSUE TITLE
about

### ISSUE THREAD

**Issue by qinxiaoyi** [fgnt/nn-gev#7]
hi,I notice that mvdr in your nn_gev code. I want to compare the performance of mvdr and gev. In beamforming.py ,the function of get_mvdr_vector. How can i set the atf_vector? Thank you for your answer.

**Comment by jheymann85** [comment]
Hi. There are many different ways to estimate the ATF.
One possible option is to use the main component of the target PSD matrix. I.e. `get_mvdr_vector(get_pca_vector(target_psd), noise_psd)`.

**Comment by qinxiaoyi** [comment]
Thank you for your answer, you mean that the ATF is like steering vector? I read the function of  get_pca_vector(target_psd), it's a common method to compute the steering vector.
