### ISSUE TITLE
Pre-trained model noise aware?

### ISSUE THREAD

**Issue by dreamibor** [fgnt/nn-gev#9]
Hi,

Are the published pre-trained models (best.nnet) trained with noise-aware data? In other words, is it trained on the simulated data? or the "clean" speech only data?

Thanks in advance.

**Comment by jheymann85** [comment]
The models in the `data` folder are trained on the simulated data from the CHiME corpus. So they are, to some extent, noise aware. But if you work with different data, I recommend training a new model to avoid a domain mismatch
